import logging

from anakonda.routing import RouteRegistry
from anakonda.request import Request
from anakonda.response import Response

logger = logging.getLogger(__name__)


class Konda(RouteRegistry):
    def __init__(self, title: str | None = None, description: str | None = None):
        super().__init__()
        self.title = title
        self.description = description
        self.routers: list = []


    def add_router(self, router) -> None:
        """
        The `add_router` function appends a router to a list and extends the routes with the router's
        routes.
        
        :param router: The `router` parameter in the `add_router` method is an object representing a network
        router. It is being added to a list of routers (`self.routers`) and its routes are being extended to
        another list of routes (`self.routes`)
        """
        self.routers.append(router)
        self.routes.extend(router.routes)


    async def __call__(self, scope: dict, receive, send) -> None:
        """
        The function is an asynchronous Python method that handles different types of scopes, such as
        "lifespan" and "http", by calling specific methods based on the scope type.
        
        :param scope: The `scope` parameter in the `__call__` method is a dictionary containing information
        about the current execution context. It typically includes details such as the type of the scope
        (e.g., "http" or "lifespan"), the path being accessed, headers, query parameters, etc
        :type scope: dict
        :param receive: The `receive` parameter in the `__call__` method is a callable that is used to
        receive messages or events from the ASGI server. It is typically used to receive incoming messages
        or events from the client, such as HTTP requests or WebSocket messages. The `receive` callable is
        asynchronous and
        :param send: The `send` parameter in the `__call__` method is a coroutine function that is used to
        send messages to the client. It is typically used to send HTTP response messages back to the client
        in the context of an HTTP connection. You can use it to send data, headers, and other
        :return: If the scope type is not "http", nothing is being returned and the function will exit
        without further action.
        """
        scope_type = scope["type"]

        if scope_type == "lifespan":
            await self._handle_lifespan(receive, send)
            return

        if scope_type != "http":
            return

        await self._handle_http(scope, receive, send)


    async def _handle_http(self, scope: dict, receive, send) -> None:
        """
        The function `_handle_http` processes incoming HTTP requests by matching routes, handling
        exceptions, and sending appropriate responses.
        
        :param scope: The `scope` parameter in the `_handle_http` method is a dictionary containing
        information about the HTTP request being handled. It typically includes details such as the type of
        request (e.g., 'http', 'websocket'), the path being accessed, headers, query parameters, etc. This
        information is used
        :type scope: dict
        :param receive: The `receive` parameter in the `_handle_http` method is used for receiving incoming
        data from the client. It is typically a coroutine that reads data from the network connection. In
        the context of an HTTP server, this parameter is used to receive the HTTP request data from the
        client, such as headers
        :param send: The `send` parameter in the `_handle_http` method is a coroutine function that is used
        to send the HTTP response back to the client. It is typically used to send the response data back to
        the client after processing the request. In this context, it is used to send the `Response`
        :return: The code snippet is returning a response based on the conditions met during the handling of
        an HTTP request. If a route is found and the method is allowed, the response generated by the
        route's handler is sent back. If an exception occurs during the handling of the request, an
        "Internal Server Error" response with a status code of 500 is sent. If the route is not found or the
        method
        """
        request = Request(scope, receive)
        path_matched = False

        for route in self.routes:
            match = route.matches(scope)

            if match is None:
                continue

            if not route.method_allowed(request.method):
                path_matched = True
                continue

            request.path_params = match

            try:
                response = await route.handler(request)
            except Exception as exc:
                logger.exception("Unhandled exception in route handler: %s", exc)
                response = Response("Internal Server Error", status=500)
                await response.send(send)
                return

            if not isinstance(response, Response):
                logger.error(
                    "Handler %r returned %r instead of a Response.",
                    route.handler,
                    type(response).__name__,
                )
                response = Response("Internal Server Error", status=500)

            await response.send(send)
            return

        response = Response("Method Not Allowed", status=405) if path_matched \
              else Response("Not Found", status=404)
        await response.send(send)


    async def _handle_lifespan(self, receive, send) -> None:
        """
        The function `_handle_lifespan` is an asynchronous function that handles startup and shutdown
        messages in a loop, executing corresponding methods and sending completion messages.
        
        :param receive: The `receive` parameter in the `_handle_lifespan` method is a coroutine function
        that is used to receive messages. It is likely implemented using an async function that waits for
        incoming messages and returns them when available. The method uses `await receive()` to receive a
        message and then processes it based
        :param send: The `send` parameter in the `_handle_lifespan` method is a coroutine function that is
        used to send messages to the lifespan protocol. It is a function that takes a message as an argument
        and sends it to the lifespan protocol. In this context, it is used to send messages indicating the
        :return: In the given code snippet, the `return` statement is used in two places within the
        `_handle_lifespan` method:
        """
        while True:
            message = await receive()

            if message["type"] == "lifespan.startup":
                try:
                    await self.on_startup()
                    await send({"type": "lifespan.startup.complete"})
                except Exception as exc:
                    logger.exception("Startup failed: %s", exc)
                    await send({"type": "lifespan.startup.failed", "message": str(exc)})
                    return

            elif message["type"] == "lifespan.shutdown":
                try:
                    await self.on_shutdown()
                finally:
                    await send({"type": "lifespan.shutdown.complete"})
                return

    async def on_startup(self) -> None:
        """Override to run logic on server startup."""

    async def on_shutdown(self) -> None:
        """Override to run logic on server shutdown."""